# Generated by Django 2.1.7 on 2019-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='learning',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='maariv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='mincha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='shacharit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
