# Generated by Django 2.1.7 on 2019-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0003_auto_20190806_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='missing',
            field=models.BooleanField(default=False),
        ),
    ]
